openapi: 3.0.1
info:
  title: API de consultório
  description: API para controlar médicos e suas especialidades dentro do consultório.
  version: 0.0.1
  termsOfService: https://mockapi.io
  contact: 
    name: Suporte a Devs
    email: contato@email.com
    url: https://mockapi.io
  license: 
    name: "Licença: GPLv3"
    url: https://www.gnu.org/licenses/gpl-3.0.pt-br.html
externalDocs:
  description: Documentação burocrática
  url: https://mockapi.io
servers:
- url: https://6096015d116f3f00174b29ba.mockapi.io/
  description: API de Teste
paths:
  /especialidades:
    get:
      summary: Recupera as especialidades
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    descricao:
                      type: string
  /especialidades/{id}:
    get:
      summary: Recupera uma entidade pelo ID
      parameters: 
      - name: id
        # Onde o parametro será enviado na requisição, se no path ou query string, etc.
        # https://swagger.io/specification/v3/#parameter-locations
        in: path
        schema:
          type: integer
        required: true
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    descricao:
                      type: string
        404:
          description: Especialidade não encontrada
          content:
            application/json:
              example: "Não achou"
          
# Query string se fosse especialidades?id=1
  # /especialidades/:
    # get:
      # summary: Recupera uma entidade pelo ID
      # parameters: 
      # - name: id
        # in: query